---
nginx_production: ""
nginx_group: "www-data"
nginx_php_force_cgi_redirect: false
nginx_user: "www-data"
nginx_worker_connections: 1024
nginx_worker_processes: "{{ ansible_processor_count }}"
nginx_www_dir: "/var/www"
nginx_error_log: "/var/log/nginx/error.log"
nginx_access_log: "/var/log/nginx/access.log"


nginx_http_params:
    client_body_timeout: "10m"
    client_header_buffer_size: "1k"
    client_header_timeout: "10m"
    connection_pool_size: 256
    ignore_invalid_headers: "on"
    keepalive_timeout: "75 20"
    large_client_header_buffers: "4 2k"
    output_buffers: "1 32k"
    postpone_output: 1460
    request_pool_size: "4k"
    send_timeout: "10m"
    sendfile: "on"
    server_names_hash_bucket_size: 64
    tcp_nodelay: "on"
    tcp_nopush: "on"
    types_hash_max_size: 2048
    ssl_protocols: "TLSv1 TLSv1.1 TLSv1.2"

nginx_set_default_server: yes
nginx_servers: []